name: Bug
description: Report something that isn’t working correctly
type: bug
projects: [Test]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug
      placeholder: "The app crashes when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions
      placeholder: "1. Do this\n2. Do that\n3. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "It should..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, it..."
    validations:
      required: true
